global using Ardalis.GuardClauses;
global using AutoMapper;
global using AutoMapper.QueryableExtensions;
global using Microsoft.EntityFrameworkCore;
global using FluentValidation;
global using MediatR;
global using CleanArchitecture.Application.Common.Interfaces;
global using CleanArchitecture.Application.Common.Models;
global using CleanArchitecture.Application.Common.Exceptions;
global using CleanArchitecture.Application.Auth.DTOs;
global using CleanArchitecture.Domain.Entities;
global using StaffEntity = CleanArchitecture.Domain.Entities.Staff;
global using CleanArchitecture.Domain.Enums;
global using CleanArchitecture.Domain.Events;
global using CleanArchitecture.Domain.Exceptions;
global using CleanArchitecture.Domain.Constants;
global using CleanArchitecture.Domain.Common;
global using CleanArchitecture.Application.Bookings.Queries.GetMyBookings;